### ISSUE TITLE
Value for BEARER, an input para to function FGIA/FGEA should be update.

### ISSUE THREAD

**Issue by eric-guanwy** [P1sec/pycrate#116]
Hi guys, first of all highly appriciate for your great work.
    I just found that there's an incorrect value for BEARER which as an input parameter for the function **FGIA( )** and **FGEA( )** in TS24501_FGMM.py from folder pycrate_mobile.  
    According to 3GPP TS33.501, **BEARER**, one of input parameters to integrity and confidentiality algorithm, shall be equal to the NAS connection identifier, and the value of the unique NAS connection identifier **shall be set to "0x01" for 3GPP access** and set to "0x02" for non-3GPP access. 
    So the bearer here should be set to 1 rather than 0. 
    But in the code the bearer always be 0, which actually not conformance to the specification. 
![image](https://user-images.githubusercontent.com/9977879/95680770-7d86e500-0c0e-11eb-9f6d-6bcb589ca8da.png)
![image](https://user-images.githubusercontent.com/9977879/95680829-d5255080-0c0e-11eb-9758-4b56e67b62ed.png)
    

    Hope these will be helpful.
    Thanks again.

**Comment by eric-guanwy** [comment]
The value of the unique NAS connection identifier updated to "0x01" for 3GPP access and "0x02" for non-3GPP access  since R15.2.0(TS33501-f20), and before this it was “0” for 3GPP access and “1” for non-3GPP access, according to TS33.501 change history.

**Comment by p1-bmu** [comment]
Thanks for the feedback. I just pushed commit https://github.com/P1sec/pycrate/commit/53ed6fe8172d87059391dbb601f8cef2ca8d7d1a that fixes this.
