### ISSUE TITLE
fix FGSIDTMSI class

### ISSUE THREAD

**Issue by Yi-Hsueh-Tsai** [P1sec/pycrate#129]
Please remove **Uint8('AMFRegionID')** from **FGSIDTMSI class** since it is not belong to 5G-S-TMSI.

class FGSIDTMSI(Envelope):
    _name = '5GSIDTMSI'
    _GEN = (
        Uint('ind', val=0xf, bl=4, rep=REPR_HEX),
        Uint('spare', bl=1),
        Uint('Type', val=FGSIDTYPE_TMSI, bl=3, dic=FGSIDType_dict),
        #Uint8('AMFRegionID'),
        Uint('AMFSetID', bl=10),
        Uint('AMFPtr', bl=6),
        Uint32('5GTMSI', rep=REPR_HEX)
        )

![image](https://user-images.githubusercontent.com/77662387/105003156-46299f00-5a6d-11eb-9136-f216b2e0f350.png)

**Comment by p1-bmu** [comment]
Thanks for reporting.
Commit https://github.com/P1sec/pycrate/commit/7a551b8dbbcfbd5738d4885f19b17951391f210b fixed this, but also changed to a more appropriate naming (S-TMSI).
