### ISSUE TITLE
Unknown extension handling

### ISSUE THREAD

**Issue by nprobert** [P1sec/pycrate#130]
I've got pycrate working with SAE J2735, which can make heavy use of extensions.  However, I do need to skip over the open and unknown extensions without the throws and warnings:

OPEN._from_per: Type.partII._item_.partII-Value, unable to retrieve a table-looked up object
ENUM._from_per: abs, unknown extension index 55
ENUM._from_per: transmission, unknown extension index 0

I do a from_uper() call, but how do I silence the warnings?

**Comment by p1-bmu** [comment]
Setting `ASN1Obj._SILENT` to `True` should solve your issue:
```
In [1]: from pycrate_asn1rt import asnobj                                                                                                                 

In [2]: asnobj.ASN1Obj._SILENT                                                                                                                            
Out[2]: False

In [3]: asnobj.ASN1Obj._SILENT = True                                                                                                                     
```

**Comment by nprobert** [comment]
Thanks!
