### ISSUE TITLE
FROM constrainsts on IA5String

### ISSUE THREAD

**Issue by jblestang** [P1sec/pycrate#150]
I'm trying to add constraints on an IA5String which shall allow from my understanding all values in the range [0;127]

```
emitterId [6] IA5String (SIZE(0..5)) (FROM({0,0} | '0'..'9' | 'A'..'Z'))
```
 Pycrate is giving me the following error when I'm trying to validate my ASN.1 : 

```
pycrate_asn1c.err.ASN1ProcTextErr: _alpha_characters: invalid IA5String value, {0,0}
```

§43.8 of [X.680](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-X.680-202102-I!!PDF-E&type=items) states that any value in the range [0;127] are authorized. I'm wondering wether my syntax/understanding of how to specify control characters is correct or if pycrate does not support expressing characters using the 'cell/row' notation.

**Comment by p1-bmu** [comment]
From the existing ASN.1 directories in pycrate, it seems double-quote is the way to go for alphabet constraints. E.g.:
```
./ITUT_H225_2009-12/H323-MESSAGES.asn:719:TBCD-STRING ::= IA5String(FROM ("0123456789#*abc"))
./ITUT_H225_2009-12/H323-MESSAGES.asn:808:IsupDigits ::= IA5String(SIZE (1..128))(FROM ("0123456789ABCDE"))
./ITUT_H245_2011-05/MULTIMEDIA-SYSTEM-CONTROL.asn:1784:		e164Address				IA5String(SIZE(1..128)) (FROM ("0123456789#*,")),
./ITUT_H245_2011-05/MULTIMEDIA-SYSTEM-CONTROL.asn:4185:		signalType				IA5String (SIZE (1) ^ FROM ("0123456789#*ABCD!")),
./OMA_LPPe/LPPe.asn:311:OMA-LPPe-CharArray ::= VisibleString(FROM ("a".."z" | "A".."Z" | "0".."9" | ".-"))(SIZE (1..31))
./OMA_ULP/ULP-Components.asn:731:          ims-public-identity              VisibleString(FROM ("a".."z" | "A".."Z" | "0".."9" | ":./-_~#@?")) (SIZE (1..255)),
```
