### ISSUE TITLE
pycrate_asn1rt.err.ASN1ObjErr: Value: value out of size constraint

### ISSUE THREAD

**Issue by ghost** [P1sec/pycrate#154]
I got an Error "out of size constraint" when I create a XnAP PDU, like this :
>>>import pycrate_asn1dir.XnAP
>>>enc=pycrate_asn1dir.XnAP.XnAP_PDU_Descriptions.XnAP_PDU
>>>a="('successfulOutcome', {'procedureCode': 10, 'criticality': 'reject', 'value': ('SNodeModificationConfirm', {'protocolIEs': [{'id': 35, 'criticality': 'ignore', 'value': ('PDUSessionAdmittedModSNModConfirm', [{'pduSessionId': 1}])}]})})"
>>>enc.set_val(a)

But, if the value of the payload has exactly 256 times {'pduSessionId': 1}, there is no error.

a=('successfulOutcome', {'procedureCode': 10, 'criticality': 'reject', 'value': ('SNodeModificationConfirm', {'protocolIEs': [{'id': 35, 'criticality': 'ignore', 'value': ('PDUSessionAdmittedModSNModConfirm', [{'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}, {'pduSessionId': 1}])}]})})

The ASN1 description for this payload is :
id-PDUSessionAdmittedModSNModConfirm                             ProtocolIE-ID ::= 35
PDUSessionAdmittedModSNModConfirm ::= SEQUENCE (SIZE(1..maxnoofPDUSessions)) OF PDUSessionAdmittedModSNModConfirm-Item
maxnoofPDUSessions     INTEGER ::= 256

Normally a sequence between 1 to 256, should be accepted.

Detailed information for debugging :

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pycrate_asn1rt/asnobj.py", line 1189, in set_val
    self._safechk_bnd(self._val)
  File "/usr/local/lib/python3.8/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 92, in _safechk_bnd
    self._cont[val[0]]._safechk_bnd(val[1])
  File "/usr/local/lib/python3.8/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 774, in _safechk_bnd
    Obj._safechk_bnd(Obj._val)
  File "/usr/local/lib/python3.8/dist-packages/pycrate_asn1rt/asnobj_ext.py", line 184, in _safechk_bnd
    self._get_val_obj(val[0])._safechk_bnd(val[1])
  File "/usr/local/lib/python3.8/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 774, in _safechk_bnd
    Obj._safechk_bnd(Obj._val)
  File "/usr/local/lib/python3.8/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 2645, in _safechk_bnd
    self._cont._safechk_bnd(v)
  File "/usr/local/lib/python3.8/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 774, in _safechk_bnd
    Obj._safechk_bnd(Obj._val)
  File "/usr/local/lib/python3.8/dist-packages/pycrate_asn1rt/asnobj_ext.py", line 184, in _safechk_bnd
    self._get_val_obj(val[0])._safechk_bnd(val[1])
  File "/usr/local/lib/python3.8/dist-packages/pycrate_asn1rt/asnobj_construct.py", line 2642, in _safechk_bnd
    raise(ASN1ObjErr('{0}: value out of size constraint, {1!r}'\
pycrate_asn1rt.err.ASN1ObjErr: Value: value out of size constraint, [{'pduSessionId': 1}]

asn1obj.construct.py (ligne 2636 to 2644)
    def _safechk_bnd(self, val):
        ASN1Obj._safechk_bnd(self, val)
        if self._const_sz and \
        self._const_sz.ext is None and \
        len(val) not in self._const_sz:
            raise(ASN1ObjErr('{0}: value out of size constraint, {1!r}'\
                  .format(self.fullname(), val)))
        for v in val:
            self._cont._safechk_bnd(v)

(_safechk_bnd)>>> self
<Value ([PDUSessionAdmittedModSNModConfirm] SEQUENCE OF)>

(_safechk_bnd)>>> val
[{'pduSessionId': 1}]

(_safechk_bnd)>>> self._const_sz
ASN1Set(root=[256], ext=None)

(_safechk_bnd)>>> len(val)
1

**Comment by greenlora** [comment]
I was using pycrate v0.5.2 upgraded to v0.5.3.
With a full uninstall and install of 0.5.3, the issue is no more present.
