### ISSUE TITLE
Typo in PNG

### ISSUE THREAD

**Issue by benjaminbecker** [P1sec/pycrate#173]
By accident I found a possible typo in PNG.py:

https://github.com/P1sec/pycrate/blob/356c5db3d8f34ecf8dcff8ad64ec7e029ee1fd86/pycrate_media/PNG.py#L63

I think in this line `_FilterMeth_dict` should be used.

If someone comfirms this, I can send a PR.

**Comment by p1-bmu** [comment]
Thanks for spotting this. Fixed with b6e12c6.
