### ISSUE TITLE
I assuming OCT_STR is not working

### ISSUE THREAD

**Issue by DVD-99** [P1sec/pycrate#176]
I have attempted to decode an uper encoded message; however, it failed to decode a key that utilizes OCT_STR()
`{'msgCnt': 11, 'id': **b'\x05\xedG\xa6'**, 'secMark'`

Could you please confirm?

**Comment by p1-bmu** [comment]
OCT_STR has been perfectly working up to now...
Please read https://github.com/P1sec/pycrate/blob/master/README.md, especially https://github.com/P1sec/pycrate/blob/master/README.md#filling-an-issue, and regarding the use of the ASN.1 runtime, read also the wiki: https://github.com/P1sec/pycrate/wiki/Using-the-pycrate-asn1-runtime.
Then you can provide all the needed information for this issue, that may be useful not only to you, but to other users of the lib. Thanks
