### ISSUE TITLE
pycrate_asn1c.proc renamed to asnproc not reflected in wiki

### ISSUE THREAD

**Issue by KenWhitesell** [P1sec/pycrate#182]
On the page https://github.com/P1sec/pycrate/wiki/Compiling-asn1-specifications, in the section on the pycrate_asn1c modules, the example still refers to pycrate_asn1c.proc instead of asnproc. Likewise, there's another such reference at https://github.com/P1sec/pycrate/wiki/Compiling-asn1-specifications#the-pycrate_asn1dir-directory to proc.py instead of asnproc.py.

I guess there's also a related question:
Is there a way for a regular user (for example, me) to supply or submit edits for the wiki pages?

**Comment by p1-bmu** [comment]
Thanks for your feedback. I fixed the incorrect references.
Regarding editing the wiki, I manage it as a git repo (see https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages, where you can git clone https://github.com/P1sec/pycrate.wiki.git). However, I am not completely sure if it is possible to submit PR for it.
