### ISSUE TITLE
pycrate_mobile documentation or examples

### ISSUE THREAD

**Issue by J93d** [P1sec/pycrate#229]
I was interested in the pycrate_mobile module, but there seems to be very less documentation/examples on the usage of it. Hopefully you find time to at least give some examples about how to use it as this seems a quite extensive project and probably the most detailed written GSM py library that I could find. Thanks for the effort.

**Comment by p1-bmu** [comment]
You can have a look on the Wiki: https://github.com/P1sec/pycrate/wiki/The-pycrate-wiki.
