### ISSUE TITLE
NGAP decoding

### ISSUE THREAD

**Issue by adad1223** [P1sec/pycrate#244]
I have raw data of Ngap message fields let it be
b'\x00\x1a\x00A\x00\x00\x03\x00\n\x00\x02\x00\x01\x00U\x00\x02\x00\x00\x00@\x00.\x00@\x01\x13~\x02\x00\x00\x00\x00\x04~\x00h\x01\x00\x04.\x01\x01\xcb\x12\x01\x16\x00\x00\x01\x00\x8c\x00\x0f\x00\x0f\x80\x7f\x00\x00\x02\xf0\x00\x00\x00\x01\xf0\x7f\x00
How do I decode this message

**Comment by p1-bmu** [comment]
You can check the Wiki which provides the related information for similar protocols, e.g.: https://github.com/P1sec/pycrate/wiki/Using-the-pycrate-asn1-runtime#the-ranap-and-s1ap-ran-protocols

**Comment by adad1223** [comment]
Thank You I got what I needed
