### ISSUE TITLE
Wrong encoding/decoding (aper) octet strings bigger than 16384 (2^14) bytes

### ISSUE THREAD

**Issue by ksiazak** [P1sec/pycrate#29]
Hi,

I discovered problem with encoding OCTET STRING with PER ALIGNED.

When I want to encode OCTET STRING with size >= 16384 bytes, pycrate returns different output than encoder available here: http://asn1-playground.oss.com/.

Here is a simple project that shows the issue:
https://github.com/ksiazak/pycrate_test_big_octet_string

Files:
- encoded_16384_len_payload.per - encoded with "ASN1 Playground" encoder OCTET STRING with content: 16384 * '\x05'
- scheme.asn1 - simple scheme containing OCTET STRING
- asn1_codecs.py - codecs generated with pycrate_asn1compile.py
- main.py - simple script that shows that data generated with pycrate and ASN1 Playground are different and pycrate cannot decode payload encoded by ASN1 Playground

For both pycrate and ASN1 Playground encoded data length is 16386 bytes but the first byte differs.
For pycrate it is \xc0 and for ASN1 Playground it is \xc1.

ASN1 Playground usage:
<img width="480" alt="asn1_playground_encoding" src="https://user-images.githubusercontent.com/14993869/46075381-a274a080-c18a-11e8-9fcc-491cd63e97f0.PNG">

**Comment by p1-bmu** [comment]
Thanks for the report.
The bug is fixed here: https://github.com/P1sec/pycrate/commit/96c332a924dc38e44f77f83312c572171129d2d7
