### ISSUE TITLE
Typo in handling of REAL

### ISSUE THREAD

**Issue by jakuis** [P1sec/pycrate#30]
https://github.com/P1sec/pycrate/blob/b53317a0a827354f07443f4fa2da86ccbb81b772/pycrate_asn1rt/asnobj_basic.py#L659

All other if-statements compare B0 (that's a zero), this one has BO (O, the letter).

**Comment by p1-bmu** [comment]
Thanks for reporting the bug.
Fixed in https://github.com/P1sec/pycrate/commit/aabf189d6ebc5b06b53d61894531c0fb19b91646
