### ISSUE TITLE
solidify static datasets

### ISSUE THREAD

**Issue by binaryflesh** [P1sec/pycrate#36]
There is several instances of using huge named tuples/dicts mixed in with python files. moving this data to a representation such as CSV or BSON and caching (Ahead-of-time if pycrate can support asynchronous execution [python 3.6+]) when called would boost performance and make importing/navigating a namespace easier.

**Comment by p1-bmu** [comment]
No named tuple are used in Pycrate, to the most of my knowledge. Could you provide few examples of huge dicts mixed in python files, that impacts the performance and make import / nagivation difficult ?

**Comment by p1-bmu** [comment]
No answer, no issue ! Closing this.
