### ISSUE TITLE
Fix inconsistent block comments with license

### ISSUE THREAD

**Issue by binaryflesh** [P1sec/pycrate#37]
an example is comparing [using library](https://github.com/P1sec/pycrate/blob/master/pycrate_sys/__init__.py#L8) and [using program](https://github.com/P1sec/pycrate/blob/master/pycrate_sys/MBR.py#L8). To save screen space could the license be in the `__init__.py` with whatever is believed to best suit the software's description?

**Comment by p1-bmu** [comment]
Thanks, aligned license header in MBR.py to LGPL with https://github.com/P1sec/pycrate/commit/565d79be99310a4d21604c410f009ec6cf1eff82
