### ISSUE TITLE
GTP Protocol

### ISSUE THREAD

**Issue by amitranjan0220** [P1sec/pycrate#40]
Can I encode and decode GTP  and UDP  protocol packets?
Please help!

**Comment by p1-bmu** [comment]
UDP format is defined here:
https://github.com/P1sec/pycrate/blob/565d79be99310a4d21604c410f009ec6cf1eff82/pycrate_ether/IP.py#L451

GTP format is not defined (also depends which GTP you need GTP-U, GTP-C, GTP', and which version). The corenet part is implementing a light GTP support, e.g.:
https://github.com/P1sec/pycrate/blob/565d79be99310a4d21604c410f009ec6cf1eff82/pycrate_corenet/ServerGTPU.py#L595

Any contribution is welcomed, thanks !
