### ISSUE TITLE
warning case-sensitive paths on a case-insensitive filesystem

### ISSUE THREAD

**Issue by l-we** [P1sec/pycrate#43]
'pycrate_asn1dir/X509_2016.json'
  'pycrate_asn1dir/x509_2016.json'
  'pycrate_asn1dir/X509_2016.py'
  'pycrate_asn1dir/x509_2016.py'

**Comment by p1-bmu** [comment]
Thanks for pointing this out: x509 has just been removed (was a duplicate of X509).
