### ISSUE TITLE
uint_bytelen returns 0 for value 0

### ISSUE THREAD

**Issue by rwincey** [P1sec/pycrate#50]
First off. awesome library. Thanks for making it public.

Second, I think I may have found a bug. The following function in "pycrate_asn1rt/utils.py" 

    def uint_bytelen(val):
       bl = val.bit_length()
       if bl % 8:
           return 1 + (bl>>3)
       else:
           return bl>>3

returns 0 byte length if the value passed is 0. Unfortunately then when it's used in PER encoding for example, if you have a field with an Integer that is set to zero, this function returns 0 and the encoded string returned is not correct. As a workaround I added

    if val == 0:
        return 1

similar to what is defined in "int_bytelen" in the same file. As this is a utility function used all over, I didn't want to presume this is the intended behavior for all of it's uses so I figured I'd put it in as an issue rather than a pull request.

**Comment by p1-bmu** [comment]
Thanks for reporting, your proposal is fine.
Fix and tests implemented in https://github.com/P1sec/pycrate/commit/b445252d5256f8e8d74af183ce0a339046dd7c00.
