### ISSUE TITLE
Encapsulate LTE NAS messages

### ISSUE THREAD

**Issue by w910820618** [P1sec/pycrate#54]
(<EMMAttachRequest : <EMMHeader : <SecHdr : 0 (No security)><ProtDisc : 7 (EMM)><Type : 65 (Attach request)>><NAS_KSI : <NAS_KSI : <TSC : 0 ( native security context)><Value : 7 (no key available)>>><EPSAttachType : <V : 2 (combined EPS / IMSI attach)>><EPSID : <L : 8><EPSID [IMSI] : 110010000000001>><UENetCap : <L : 4><UENetCap : <EEA0 : 1><EEA1_128 : 1><EEA2_128 : 1><EEA3_128 : 1><EEA4 : 0><EEA5 : 0><EEA6 : 0><EEA7 : 0><EIA0 : 1><EIA1_128 : 1><EIA2_128 : 1><EIA3_128 : 1><EIA4 : 0><EIA5 : 0><EIA6 : 0><EIA7 : 0><UEA0 : 1><UEA1 : 1><UEA2 : 0><UEA3 : 0><UEA4 : 0><UEA5 : 0><UEA6 : 0><UEA7 : 0><UCS2 : 1><UIA1 : 1><UIA2 : 0><UIA3 : 0><UIA4 : 0><UIA5 : 0><UIA6 : 0><UIA7 : 0><ProSe_dd [transparent] : 0><ProSe [transparent] : 0><H245_ASH [transparent] : 0><ACC_CSFB [transparent] : 0><LPP [transparent] : 0><LCS [transparent] : 0><X1_SRVCC [transparent] : 0><NF [transparent] : 0><ePCO [transparent] : 0><HC_CP_CIoT [transparent] : 0><ERw_oPDN [transparent] : 0><S1U_data [transparent] : 0><UP_CIoT [transparent] : 0><CP_CIoT [transparent] : 0><ProSe_relay [transparent] : 0><ProSe_dc [transparent] : 0><spare [transparent] : 0><spare [transparent] : 0><spare [transparent] : 0><spare [transparent] : 0><spare [transparent] : 0><spare [transparent] : 0><spare [transparent] : 0><MultiDRB [transparent] : 0><spare [transparent] : 0x>>><ESMContainer : <L : 44><ESMPDNConnectivityRequest : <ESMHeader : <EPSBearerId : 0><ProtDisc : 2><PTI : 1><Type : 208 (PDN connectivity request)>><PDNType : <V : 3 (IPv4v6)>><RequestType : <V : 1 (Initial request)>><ESMInfoTransferFlag [transparent] : <T : 13><V : 0>><APN [transparent] : <T : 40><L : 1><V : 0x00>><ProtConfig : <T : 39><L : 38><ProtConfig : <Ext : 1><spare : 0><Prot : 0 (PPP with IP PDP)><Config : <ProtConfigElt : <ID : 32801 (IPCP)><Len : 16><Cont : <Code : 1 (Configure-Request)><Id : 1><Len : 16><Data : <NCPOpt : <Type : 129 (Primary DNS Server Address)><Len : 6><Data : 0x00000000>><NCPOpt : <Type : 131 (Secondary DNS Server Address)><Len : 6><Data : 0x00000000>>>>><ProtConfigElt : <ID : 3 (DNS Server IPv6 Address Request)><Len : 0><Cont : 0x>><ProtConfigElt : <ID : 10 (IP address allocation via NAS signalling)><Len : 0><Cont : 0x>><ProtConfigElt : <ID : 2 (IM CN Subsystem Signaling Flag)><Len : 0><Cont : 0x>><ProtConfigElt : <ID : 12 (P-CSCF IPv4 Address)><Len : 0><Cont : 0x>><ProtConfigElt : <ID : 1 (P-CSCF IPv6 Address Request)><Len : 0><Cont : 0x>><ProtConfigElt : <ID : 13 (DNS server IPv4 address request)><Len : 0><Cont : 0x>>>>><DeviceProp [transparent] : <T : 12><V : 0>><NBIFOMContainer [transparent] : <T : 51><L : 1><V : 0x00>><HdrCompConfig [transparent] : <T : 102><L : 3><V : 0x000000>><ExtProtConfig [transparent] : <T : 123><L : 1><V : 0x00>>>><OldPTMSISign [transparent] : <T : 25><V : 0x000000>><AddGUTI [transparent] : <T : 80><L : 11><V : 0xf600000000000000000000>><OldTAI [transparent] : <T : 82><V : 0x0000000000>><DRXParam : <T : 92><DRXParam : <SPLIT_PG_CYCLE_CODE : 32><DRXCycleLen : 0 (DRX not specified by the MS)><SPLITonCCCH : 0><NonDRXTimer : 0 (no non-DRX mode after transfer state)>>><MSNetCap : <T : 49><L : 3><ms_network_capability_value_part (CSN1List): [<(CSN1Ref): <gea1_bits (CSN1Bit): 1>><sm_capabilities_via_dedicated_channels (CSN1Bit): 1><sm_capabilities_via_gprs_channels (CSN1Bit): 1><ucs2_support (CSN1Bit): 0><ss_screening_indicator (CSN1Bit): 1><solsa_capability (CSN1Bit): 0><revision_level_indicator (CSN1Bit): 1><pfc_feature_mode (CSN1Bit): 0><(CSN1Ref): <extended_gea_bits (CSN1List): [<gea_2 (CSN1Bit): 1><gea_3 (CSN1Bit): 1><gea_4 (CSN1Bit): 0><gea_5 (CSN1Bit): 0><gea_6 (CSN1Bit): 0><gea_7 (CSN1Bit): 0>]>><lcs_va_capability (CSN1Bit): 0><ps_inter_rat_ho_from_geran_to_utran_iu_mode_capability (CSN1Bit): 0><ps_inter_rat_ho_from_geran_to_e_utran_s1_mode_capability (CSN1Bit): 0><emm_combined_procedures_capability (CSN1Bit): 1><isr_support (CSN1Bit): 1><srvcc_to_geran_utran_capability (CSN1Bit): 1><epc_capability (CSN1Bit): 1><nf_capability (CSN1Bit): 0><geran_network_sharing_capability (CSN1Bit): 0>]>><OldLAI [transparent] : <T : 19><V : 0x0000000000>><TMSIStatus : <T : 9><TMSIStatus : <spare : 0><Flag : 0 (no valid TMSI available)>>><MSCm2 : <T : 17><L : 3><MSCm2 : <spare : 0><RevLevel : 2 (MS supporting R99 or later)><EarlyCmCap : 1><NoA51 : 0><RFClass : 7><spare : 0><PSCap : 1><SSScreeningCap : 1 (capability of handling of ellipsis notation and phase 2 error handling)><MTSMSCap : 1><VBSNotifCap : 0><VGCSNotifCap : 0><FCFreqCap : 0><MSCm3Cap : 1><spare : 0><LCSVACap : 0><UCS2 : 0><SoLSACap : 0><CMServPrompt : 1><A53 : 1><A52 : 0>>><MSCm3 : <T : 32><L : 9><classmark_3_value_part (CSN1List): [<(CSN1Ref): <spare_bit (CSN1Bit): 0>><(CSN1Alt): { 110 (multiband_supported) : [<(CSN1Ref): <a5_bits (CSN1List): [<a5_7 (CSN1Bit): 0><a5_6 (CSN1Bit): 0><a5_5 (CSN1Bit): 0><a5_4 (CSN1Bit): 0>]>><associated_radio_capability_2 (CSN1Bit): 1><associated_radio_capability_1 (CSN1Bit): 4>]}><(CSN1Alt): { 0 : []}><(CSN1Alt): { 0 : []}><ucs2_treatment (CSN1Bit): 0><extended_measurement_capability (CSN1Bit): 0><(CSN1Alt): { 0 : []}><(CSN1Alt): { 0 : []}><(CSN1Alt): { 0 : []}><(CSN1Alt): { 0 : []}><(CSN1Alt): { 0 : []}><(CSN1Alt): { 1 : [<gsm_850_associated_radio_capability (CSN1Bit): 4>]}><(CSN1Alt): { 1 : [<gsm_1900_associated_radio_capability (CSN1Bit): 1>]}><umts_fdd_radio_access_technology_capability (CSN1Bit): 1><umts_3_84_mcps_tdd_radio_access_technology_capability (CSN1Bit): 0><cdma_2000_radio_access_technology_capability (CSN1Bit): 0><(CSN1Alt): { 0 : []}><(CSN1Alt): { 0 : []}><(CSN1Alt): { 0 : []}><umts_1_28_mcps_tdd_radio_access_technology_capability (CSN1Bit): 0><geran_feature_package_1 (CSN1Bit): 1><(CSN1Alt): { 0 : []}><(CSN1Alt): { 0 : []}><(CSN1Val): 0><geran_feature_package_2 (CSN1Bit): 0><gmsk_multislot_power_profile (CSN1Bit): 0><_8_psk_multislot_power_profile (CSN1Bit): 0><(CSN1Alt): { 0 : []}><(CSN1Val): 0><downlink_advanced_receiver_performance (CSN1Bit): 1><dtm_enhancements_capability (CSN1Bit): 0><(CSN1Alt): { 0 : []}><repeated_acch_capability (CSN1Bit): 1><(CSN1Alt): { 0 : []}><(CSN1Alt): { 0 : []}><ciphering_mode_setting_capability (CSN1Bit): 0><additional_positioning_capabilities (CSN1Bit): 0><e_utra_fdd_support (CSN1Bit): 1><e_utra_tdd_support (CSN1Bit): 1><e_utra_measurement_and_reporting_support (CSN1Bit): 1><priority_based_reselection_support (CSN1Bit): 1><utra_csg_cells_reporting (CSN1Bit): 0><vamos_level (CSN1Bit): 0><tighter_capability (CSN1Bit): 0><selective_ciphering_of_downlink_sacch (CSN1Bit): 0>]>><SuppCodecs : <T : 64><L : 8><SuppCodecList : <SuppCodec : <SysID : 4><BMLen : 2><CodecBM : 0b0110000000000000>><SuppCodec : <SysID : 0><BMLen : 2><CodecBM : 0b0001111100000000>>>><AddUpdateType [transparent] : <T : 15><V : 0>><VoiceDomPref : <T : 93><L : 1><VoiceDomPref : <spare : 0><UEUsage : 0 (Voice centric)><VoiceDomPref : 0 (CS Voice only)>>><DeviceProp [transparent] : <T : 13><V : 0>><OldGUTIType [transparent] : <T : 14><V : 0>><MSNetFeatSupp [transparent] : <T : 12><V : 0>><TMSIBasedNRICont [transparent] : <T : 16><L : 2><V : 0x0000>><T3324 [transparent] : <T : 106><L : 1><V : 0x00>><T3412Ext [transparent] : <T : 94><L : 1><V : 0x00>><ExtDRXParam [transparent] : <T : 110><L : 1><V : 0x00>>>, 0)

This is the Attach request NAS message that I parsed through pycrate. Can you give a packaged example?

**Comment by p1-bmu** [comment]
Sorry again, same answer as for issue#53.
