### ISSUE TITLE
parsing NAS

### ISSUE THREAD

**Issue by w910820618** [P1sec/pycrate#55]
Which method is the method of parsing NAS?

**Comment by w910820618** [comment]
I ask, is your program working as I described it?
1. First determine which NAS signaling belongs to by parsing the NAS packet.
2. Load NAS signaling into memory
3. Use the _from_char method of each IE in the signaling to parse

**Comment by p1-bmu** [comment]
Parsing NAS messages is explained in the wiki: https://github.com/P1sec/pycrate/wiki/Mobile-nas-messages.
How it is done technically is a little bit complex, all NAS messages are subclass of Layer3, see https://github.com/P1sec/pycrate/blob/786a69b36f313c6ccfdf989bf5787e3e05e2c3a8/pycrate_mobile/TS24007.py#L68.

**Comment by w910820618** [comment]
![image](https://user-images.githubusercontent.com/22961061/62114506-64d02f00-b2e9-11e9-805a-e86ad963b767.png)
Why can't I assign an EPSID like this?

**Comment by p1-scg** [comment]
p1-bmu 不可以随便帮助你

**Comment by w910820618** [comment]
哦，知道了
