### ISSUE TITLE
MSNetCap and ESMContainer are assigned on AttachRequest

### ISSUE THREAD

**Issue by w910820618** [P1sec/pycrate#56]
Sorry, I am bothering you again, because I don’t know how to solve the two problems now. I hope you can give me some tips. I tried to assign the two IEs ESMContainer and MSNetCap in the NAS message of AttachRequest, but it always went wrong. I don't know where the problem is, I hope I can point it out.

input value:
`ESMContainer : [44, [[0, 2, 1, 208], [3], [1], [39, 38, [1, 0, 0, [[32801, 16, [1, 1, 16, [[129, 6, b'\x00\x00\x00\x00'], [131, 6, b'\x00\x00\x00\x00']]]], [3, 0, b''], [10, 0, b''], [2, 0, b''], [12, 0, b''], [1, 0, b''], [13, 0, b'']]]]]]
MSNetCap : [49, 3, [1, 1, 1, 0, 1, 0, 1, 0, [1, 1, 0, 0, 0, 0], 0, 0, 0, 1, 1, 1, 1, 0, 0]]
`
output value:
`ESMContainer : [0, b'']
MSNetCap : [49, 39, [0, 0, 1, 0, 1, 1, 0, 1, [0, 0, 0, 0, 0, 0], 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]]]
`
Assignment process：
`PDNConnectivityRequest = ESMPDNConnectivityRequest()
        PDNConnectivityRequest['ESMHeader'].set_val([0, 2, 1, 208])
        PDNConnectivityRequest['PDNType'].set_val([3])
        PDNConnectivityRequest['RequestType'].set_val([1])
        PDNConnectivityRequest['ProtConfig'].set_trans(False)
        PDNConnectivityRequest['ProtConfig'].set_val([39, 38, [1, 0, 0, [
            [32801, 16, [1, 1, 16, [[129, 6, b'\x00\x00\x00\x00'], [131, 6, b'\x00\x00\x00\x00']]]], [3, 0, b''],
            [10, 0, b''], [2, 0, b''], [12, 0, b''], [1, 0, b''], [13, 0, b'']]]])
        Msg['ESMContainer'].set_val({'V': PDNConnectivityRequest.to_bytes()})

 Msg['MSNetCap'].set_trans(False)
 Msg['MSNetCap'].set_val({'T': 49, 'V': [1, 1, 1, 0, 1, 0, 1, 0, [1, 1, 0, 0, 0, 0], 0, 0, 0, 1, 1, 1, 1, 0, 0]})
`

**Comment by p1-scg** [comment]
够了，你自己来做.
