### ISSUE TITLE
About NAS codec

### ISSUE THREAD

**Issue by w910820618** [P1sec/pycrate#57]
Hello, I am sorry to always bother you to help you solve the problem. I have successfully packaged a NAS message.
I have a few questions, I want to ask you, google has not been able to find an answer for a long time.
1. Why not use asn.1 as a codec tool for NAS messages?
2. What is the role of CSN.1 in NAS message encoding and decoding? Why can't I use asn.1 instead?

I have read the introduction of csn.1 on the website http://csn1.info. It also mentions that the protocol TS24.007 and TS24.008 have the format encoding MSNetCap using csn.1. But I don't know why I have to write it.

I hope I can receive the answer, thank you.****

**Comment by p1-bmu** [comment]
You must ask those questions to the people who designed the NAS protocols: https://www.3gpp.org/specifications-groups/ct/ct1-mm-cc-sm-lu/home
