### ISSUE TITLE
How to validate a message?

### ISSUE THREAD

**Issue by ejdoh1** [P1sec/pycrate#76]
Hello,

Can you please guide me on how to validate a message against an ASN1 doc?

For instance, the from_json method seems to be happy if the json supplied does not contain all required fields, however set_val errors saying 'missing mandatory value'.

**Comment by p1-bmu** [comment]
Can you provide more contextual information please ?
- the version of pycrate you are using
- an example that exhibits the issue you found
Thanks

**Comment by p1-bmu** [comment]
Maybe commit https://github.com/P1sec/pycrate/commit/2d95a525a00815e55d81f8705e6959759d636417 will answer to your question ?
