### ISSUE TITLE
Encoding messages: Names & Structure

### ISSUE THREAD

**Issue by mrlnc** [P1sec/pycrate#83]
Hi everybody!

Thanks for creating pycrate. I've used it for decoding in the past, but now I'd like to *encode* S1AP/NGAP messages. The wiki has some examples [here](https://github.com/P1sec/pycrate/wiki/Using-the-pycrate-asn1-runtime#s1ap):
```
PDU = S1AP.S1AP_PDU_Descriptions.S1AP_PDU
IEs = []
IEs.append({'id': 8, 'value': ('ENB-UE-S1AP-ID', 1202), 'criticality': 'reject'})
IEs.append({'id': 100, 'value': ('EUTRAN-CGI', {'cell-ID': (1, 28), 'pLMNidentity': b'\x00\x01\xf1'}), 'criticality': 'ignore'})
...
val = ('initiatingMessage', {'procedureCode': 12, 'value': ('InitialUEMessage', {'protocolIEs': IEs}), 'criticality': 'ignore'})
PDU.set_val(val)
```

My question is simply: How do I know the IE must be structured in that way?

Say I need to add `EUTRAN-CGI`, I'd now check the ID first:
```
>>> S1AP.S1AP_Constants.id_EUTRAN_CGI
<id-EUTRAN-CGI ([ProtocolIE-ID] INTEGER): 100>
```
Then check the structure:
```
>>> S1AP.S1AP_IEs.EUTRAN_CGI._cont
{
pLMNidentity: <pLMNidentity ([PLMNidentity] OCTET STRING)>,
cell-ID: <cell-ID ([CellIdentity] BIT STRING)>,
iE-Extensions: <iE-Extensions ([ProtocolExtensionContainer] SEQUENCE OF)>
}
```

Still, this somehow feels wrong and I'd expect my IDE to assist me here. Like… `S1AP.S1AP_IEs.EUTRAN_CGI.<tab>` to show me its IEs to fill in.

I feel like I missed something stupid here, but couldn't figure it out reading through the examples. Help much appreciated.

**Comment by p1-bmu** [comment]
I am not using personally any advanced IDE. When building values and structures for ASN.1 objects, I use directly the ASN.1 textual definition or an interactive interpreter with the loaded module (as you mention here).
I am not aware of any IDE with support for ASN.1 features (such as name completion...).

If you want simple completion with the <tab> within a simple interpreter such as ipython, it may be possible to easily build an object's tree where SEQUENCE / CHOICE content are attributes of parents objects.

There is also a `get_proto()` method available for every ASN.1 objects, which is not perfect but can be useful regarding your need.
