### ISSUE TITLE
Creating an object based on ASN.1 value notation file to use to_ber()

### ISSUE THREAD

**Issue by danny4478** [P1sec/pycrate#91]
I have 2 files:

1. ASN.1 **schema** file
2. ASN.1 **value notation** file - File with specific values matching the ASN.1 schema file (have it in TXT format, and also in JSON and XML formats)

I have manged to compile ASN.1 schema file using _compile_text()_.
I am trying to figure out how I can encode file **2** into BER or UPER.
I basically don't understand how to create an object from file 2 so I can use the _to_ber()_ method.

Thanks

**Comment by p1-bmu** [comment]
You should start with reading the wiki: https://github.com/P1sec/pycrate/wiki/Compiling-asn1-specifications and https://github.com/P1sec/pycrate/wiki/Using-the-pycrate-asn1-runtime
When loading a Python module generated by the ASN.1 compiler, all ASN.1 objects have docstrings, to explain supported format and type for values.
